services:
    exs_feeds_awe.memcached:
        class: '\Memcached'
        calls:
            - ['addServer', ['%exs_feeds_awe.memcached_host%', '%exs_feeds_awe.memcached_port%']]

    exs_feeds_awe.memcached.http_client:
        class: 'GuzzleHttp\Client'

    exs_feeds_awe.feeds_reader:
        class: 'EXS\FeedsAWEBundle\Service\FeedsReader'
        arguments:
            - '@exs_feeds_awe.memcached'
            - '@exs_feeds_awe.memcached.http_client'
            - '%exs_feeds_awe.cache_ttl%'
